sudo: required
language: python

python:
  - "2.7"

services:
  - docker

before_install:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker build -t elliptic .

install:
- pip install python-coveralls

script:
- docker run elliptic /bin/bash -c "python setup.py test"

after_success:
# Fixing coverage paths:
# https://github.com/pytest-dev/pytest-cov/issues/146
- docker cp `docker ps -l -q`:/home/scientific/ELLIPTIc/.coverage .coverage.docker
- coverage combine
- coveralls
- docker tag elliptic gpkc/elliptic
- if [ "$TRAVIS_BRANCH" == "master" ]; then
  docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  docker push gpkc/elliptic;
  fi
